### PR TITLE
No armor testing

### PR DESCRIPTION
**Pull request by Darkon47**

### CODE REVIEW

**Comment by Darkon47** [comment]
Sorry, wrong merge, meant to merge into my local

**Comment by EzioTheDeadPoet** [comment]
Oh what is that edit about ?
Looks interesting.

**Comment by Darkon47** [comment]
made a quick rewrite last night so that it would handle a greater spread of qualities. the current version can fail to generate even 3 qualities if you have too many enchantments/items for it to pick from.

**Comment by EzioTheDeadPoet** [comment]
If you want, and have it working make a PR to add it here as this purposefully isn't my repository so more people can more easily work on it.

**Pull request closed without merging**
